sudo: required
services:
  - docker 

before_install:
  - docker build -t stephanielamb321/docker-react -f Dockerfile.dev . 

script:
  - docker run stephanielamb321/docker-react npm run test -- --coverage